// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnnsOnDGy84xq268XxJIJqlPbm_jHLj_8',
    appId: '1:888439433524:web:645380958256e9419bdd61',
    messagingSenderId: '888439433524',
    projectId: 'example-259ac',
    authDomain: 'example-259ac.firebaseapp.com',
    storageBucket: 'example-259ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnespxPm8ZA6HJTe6zVHQOhi4Yp_Wdz4',
    appId: '1:888439433524:android:21ca6ae6cac4e7e29bdd61',
    messagingSenderId: '888439433524',
    projectId: 'example-259ac',
    storageBucket: 'example-259ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAib9yxGUetIw0-ZYkXPPZWU7HUBBK3Ic',
    appId: '1:888439433524:ios:079a7fd7112fe90b9bdd61',
    messagingSenderId: '888439433524',
    projectId: 'example-259ac',
    storageBucket: 'example-259ac.appspot.com',
    iosBundleId: 'com.example.miniProject3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnnsOnDGy84xq268XxJIJqlPbm_jHLj_8',
    appId: '1:888439433524:web:f42540523a6c16249bdd61',
    messagingSenderId: '888439433524',
    projectId: 'example-259ac',
    authDomain: 'example-259ac.firebaseapp.com',
    storageBucket: 'example-259ac.appspot.com',
  );
}
